### ISSUE TITLE
Show all time and distance not working

### ISSUE THREAD

**Issue by jaha6145** [trtr3104/Tran_CSCI2270_FinalProject#3]
Menu item 7 only calls for a starting city and once entered, (whether it is an existing city or not) only returns menu

**Comment by trtr3104** [comment]
I am not sure where you are getting that problem because mine works fine. So the menu item #7 asks you for a city. And once you enter that city, it will return all the cities that you can go from the starting city, along with the time and distance it takes you get there. I have attached an example. 
![selection 7](https://cloud.githubusercontent.com/assets/18508346/14906557/c2ddeae2-0d79-11e6-8f0a-953c5087ddf6.png)

Please let me know if it still isn't working for you.

**Comment by jaha6145** [comment]
Here is the output I am receiving. I will try to clone your project to my VM again and see if this fixes the issue.
<img width="365" alt="tran_option_7" src="https://cloud.githubusercontent.com/assets/18423213/14925722/02e8984e-0e06-11e6-8183-628975dbbad3.png">

**Comment by trtr3104** [comment]
This is what I am getting.
![virtualbox_cu-cs-vm-spring16-xfce-x64_01_05_2016_02_05_53](https://cloud.githubusercontent.com/assets/18508346/14940806/cbc88d50-0f41-11e6-9d51-0c561bd5e1cd.png)

Again, please check your text file. Thanks!

**Comment by jaha6145** [comment]
Everything is working on my end.
